import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Urbanist } from 'next/font/google';
import { AuthContextProvider } from '@/app/context/AuthContext';
import Footer from "./components/Footer";

const urbanist = Urbanist({
  subsets: ['latin'],
  variable: '--font-urbanist',
  weight: ['400', '500', '600', '700'], // Adjust weights needed
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Alaskago",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.variable}`}  
      > 
      
           <AuthContextProvider> {children}</AuthContextProvider>
       
      <Footer/>
      </body>
    </html>
  );
}
